ALTER TABLE `BRANCHES` RENAME COLUMN `name` TO `branch_name`;
ALTER TABLE `BRANCHES` ADD COLUMN `is_active` BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE `REPORT_LOG` RENAME COLUMN `file_path` TO `file_location`;

ALTER TABLE `REPORT_SCHEDULE` RENAME COLUMN `time` TO `daily_time`;

ALTER TABLE `SALES` ADD COLUMN `tax` DECIMAL(10, 2) NOT NULL DEFAULT 0;