-- DropForeignKey
ALTER TABLE `TENANT_SUBSCRIPTIONS` DROP FOREIGN KEY `TENANT_SUBSCRIPTIONS_branch_id_fkey`;

-- DropIndex
DROP INDEX `TENANT_SUBSCRIPTIONS_branch_id_fkey` ON `TENANT_SUBSCRIPTIONS`;

-- AlterTable
ALTER TABLE `SUBSCRIPTION_PLANS` ADD COLUMN `max_branches` INTEGER NULL,
    ADD COLUMN `max_users` INTEGER NULL;

-- AlterTable
ALTER TABLE `TENANT_SUBSCRIPTIONS` DROP COLUMN `branch_id`,
    ADD COLUMN `business_id` INTEGER NOT NULL;

-- AddForeignKey
ALTER TABLE `TENANT_SUBSCRIPTIONS` ADD CONSTRAINT `TENANT_SUBSCRIPTIONS_business_id_fkey` FOREIGN KEY (`business_id`) REFERENCES `BUSINESSES`(`business_id`) ON DELETE RESTRICT ON UPDATE CASCADE;