-- CreateTable
CREATE TABLE `PAYMENT_TRANSACTIONS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `reference` VARCHAR(100) NOT NULL,
    `amount` DECIMAL(10, 2) NOT NULL,
    `currency` VARCHAR(3) NOT NULL DEFAULT 'NGN',
    `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    `provider` VARCHAR(20) NOT NULL DEFAULT 'PAYSTACK',
    `channel` VARCHAR(20) NULL,
    `paid_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `business_id` INTEGER NOT NULL,
    `subscription_id` INTEGER NOT NULL,

    UNIQUE INDEX `PAYMENT_TRANSACTIONS_reference_key`(`reference`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PAYMENT_TRANSACTIONS` ADD CONSTRAINT `PAYMENT_TRANSACTIONS_business_id_fkey` FOREIGN KEY (`business_id`) REFERENCES `BUSINESSES`(`business_id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PAYMENT_TRANSACTIONS` ADD CONSTRAINT `PAYMENT_TRANSACTIONS_subscription_id_fkey` FOREIGN KEY (`subscription_id`) REFERENCES `TENANT_SUBSCRIPTIONS`(`subscription_id`) ON DELETE RESTRICT ON UPDATE CASCADE;
