-- AlterTable
ALTER TABLE `CARTS` ADD COLUMN `discount` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `subtotal` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `tax` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `total` DECIMAL(10, 2) NOT NULL DEFAULT 0;