-- AlterTable
ALTER TABLE `CATEGORIES` ADD COLUMN `business_id` INTEGER NULL;

-- AlterTable
ALTER TABLE `SUPPLIERS` ADD COLUMN `business_id` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `CATEGORIES` ADD CONSTRAINT `CATEGORIES_business_id_fkey` FOREIGN KEY (`business_id`) REFERENCES `BUSINESSES`(`business_id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SUPPLIERS` ADD CONSTRAINT `SUPPLIERS_business_id_fkey` FOREIGN KEY (`business_id`) REFERENCES `BUSINESSES`(`business_id`) ON DELETE SET NULL ON UPDATE CASCADE;